version: '3'
networks:
  dev:
    driver: bridge
services:
  viewer:
    container_name: viewer
    image: alexmass/bokm-viewer:latest
    restart: unless-stopped
    networks:
      - dev
  mbtileserver:
    container_name: mbtileserver
    image: alexmass/bokm-mbtileserver:latest
    restart: unless-stopped
    networks:
      - dev
  nginx:
    container_name: nginx
    image: alexmass/bokm-nginx:latest
    restart: always
    ports:
      - '9080:80'
    depends_on:
      - viewer
      - mbtileserver
    networks:
      - dev